import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import type { NewFact } from "../../core/types.js";
import { type ExtractContext, type Extractor, structuredFact } from "./types.js";

const GENERATED_MARKERS = [
  "@generated",
  "DO NOT EDIT",
  "Code generated by",
  "autogenerated",
  "This file is auto-generated",
];

const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "build", "coverage", ".graphctx"]);
const MAX_FILES = 400;

// Scans for files declaring themselves generated ("do not edit" boundaries).
export const generatedMarkersExtractor: Extractor = {
  id: "generated-markers",
  extract(ctx: ExtractContext): NewFact[] {
    const generated: string[] = [];
    let scanned = 0;
    const walk = (dir: string): void => {
      if (scanned >= MAX_FILES) return;
      let entries: string[];
      try {
        entries = readdirSync(dir);
      } catch {
        return;
      }
      for (const entry of entries) {
        if (scanned >= MAX_FILES) return;
        if (SKIP_DIRS.has(entry)) continue;
        const full = join(dir, entry);
        let st: ReturnType<typeof statSync>;
        try {
          st = statSync(full);
        } catch {
          continue;
        }
        if (st.isDirectory()) {
          walk(full);
        } else if (st.isFile() && isSource(entry) && st.size < 200_000) {
          scanned++;
          try {
            const head = readFileSync(full, "utf8").slice(0, 600);
            if (GENERATED_MARKERS.some((m) => head.includes(m))) {
              generated.push(relative(ctx.workspaceDir, full));
            }
          } catch {
            // skip unreadable
          }
        }
      }
    };
    walk(ctx.workspaceDir);
    if (generated.length === 0) return [];

    const facts: NewFact[] = [];
    for (const file of generated.slice(0, 20)) {
      facts.push(
        structuredFact({
          subject: file,
          predicate: "do_not_edit",
          object: true,
          fact_kind: "constraint",
          temporal_kind: "static",
          scope: ctx.scope,
          tags: ["generated_code", "config_file"],
          rawQuote: `${file} is generated; do not edit by hand`,
          git: {
            repo_id: ctx.repoId,
            branch: ctx.branch,
            valid_from_commit: ctx.head,
            path_globs: [file],
          },
        }),
      );
    }
    return facts;
  },
};

function isSource(name: string): boolean {
  return /\.(ts|tsx|js|jsx|go|py|rs|java|cs|rb|sql|graphql|proto)$/.test(name);
}
