// Builds self-contained graphctx binaries with `bun build --compile`.
//
// For each target platform we:
//   1) write src/store/vec0-embed.generated.ts that imports the matching
//      vendored sqlite-vec extension as an embedded file (Bun bakes it in).
//   2) run `bun build --compile --target=<bun-target>` to emit one executable
//      with no Node, npm, or node_modules dependency.
//
// Output: dist-bin/graphctx-<platform> (+ .sha256).
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { createHash as hash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const vendor = join(root, "vendor", "vec0");
const outDir = join(root, "dist-bin");
const embedFile = join(root, "src", "store", "vec0-embed.generated.ts");

// platform → { bunTarget, vec0 file, output name }
const TARGETS = [
  { name: "linux-x64", bun: "bun-linux-x64", vec0: "vec0-linux-x64.so" },
  { name: "linux-arm64", bun: "bun-linux-arm64", vec0: "vec0-linux-arm64.so" },
  { name: "darwin-x64", bun: "bun-darwin-x64", vec0: "vec0-darwin-x64.dylib" },
  { name: "darwin-arm64", bun: "bun-darwin-arm64", vec0: "vec0-darwin-arm64.dylib" },
];

const only = process.argv[2]; // optional: build a single platform

mkdirSync(outDir, { recursive: true });

const STUB = `// Default stub (Node/dev/tests). Overwritten per-platform by
// scripts/build-binary.mjs before \`bun build --compile\`, then restored. Under
// Node the vector layer loads sqlite-vec from npm, so no embedded extension is
// needed here.
const vec0: string | undefined = undefined;
export default vec0;
`;

for (const t of TARGETS) {
  if (only && only !== t.name) continue;
  const vec0Path = join(vendor, t.vec0);
  if (!existsSync(vec0Path)) {
    console.error(`! skip ${t.name}: missing ${vec0Path}`);
    continue;
  }

  // 1) point the embed module at this platform's extension. Bun resolves the
  //    `with { type: "file" }` import and bakes the bytes into the binary; the
  //    default export is the extracted on-disk path at runtime.
  const rel = `../../vendor/vec0/${t.vec0}`;
  writeFileSync(
    embedFile,
    `// AUTO-GENERATED by scripts/build-binary.mjs for target ${t.name}.\n` +
      `import vec0 from "${rel}" with { type: "file" };\n` +
      `export default vec0;\n`,
  );

  // 2) compile.
  const outFile = join(outDir, `graphctx-${t.name}`);
  console.log(`→ building ${t.name} → ${outFile}`);
  execFileSync(
    "bun",
    [
      "build",
      "--compile",
      `--target=${t.bun}`,
      join(root, "src", "cli.ts"),
      "--outfile",
      outFile,
    ],
    { stdio: "inherit", cwd: root },
  );

  // 3) checksum.
  const buf = readFileSync(outFile);
  const sum = hash("sha256").update(buf).digest("hex");
  writeFileSync(`${outFile}.sha256`, `${sum}  graphctx-${t.name}\n`);
  console.log(`✓ ${t.name}  sha256 ${sum.slice(0, 16)}…  ${(buf.length / 1e6).toFixed(1)}MB`);
}

// Restore the stub so tsc / tests / npm builds resolve a real TS module rather
// than a per-platform binary import.
writeFileSync(embedFile, STUB);
console.log("done.");
